resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
resources:
- name: pivnet-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: {{pivnet_product_slug}}
    sort_by: semver
- name: pivnet-monitor
  type: git
  source:
    uri: git@github.com:ecsteam/pivnet-monitor.git
    branch: master
    private_key: {{git_private_key}}
- name: schedule
  type: time
  source:
    interval: 30m
    start: "12:00 AM"
    stop: "11:59 PM"
    location: America/Denver
jobs:
- name: regulator
  plan:
    - get: schedule
      trigger: true
    - get: pivnet-product
      params: { globs: [] }
      trigger: true
- name: start-pipeline
  plan:
  - aggregate:
    - get: pivnet-monitor
    - get: pivnet-product
      params: { globs: [] }
      trigger: true
      passed: [regulator]
  - task: start-pipeline-job
    file: pivnet-monitor/tasks/start-pipeline-job/task.yml
    params:
      CONCOURSE_URL: {{concourse_url}}
      CONCOURSE_USER: {{concourse_user}}
      CONCOURSE_PWD: {{concourse_pwd}}
      PIPELINE_NAME: {{pipeline_name}}
      JOB_NAME: {{job_name}}
