---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu/trusty}

inputs:
  - name: pivnet-monitor

params:
  CONCOURSE_URL:
  CONCOURSE_USER:
  CONCOURSE_PWD:
  PIPELINE_NAME:
  JOB_NAME:

run:
  path: pivnet-monitor/tasks/start-pipeline-job/task.sh
